# branches:
#   only:
#     - master
jobs:
  include:
    - language: nix
      addons:
        apt:
          packages:
            - lcov
            - gcov
      install:
        - "nix-env -iA cachix -f https://cachix.org/api/v1/install"
      script:
        - if ["$TRAVIS_BRANCH" == "master"]; then cachix use dseams; fi
        - if ["$TRAVIS_BRANCH" == "master"]; then cachix push dseams   --watch-store&; fi
        - nix-build .
        - if ["$TRAVIS_BRANCH" == "master"]; then sleep 30s; fi # wait for the cachix push to complete
      cache: nix
      after_success:
        - make testCoverage
        - bash <(curl -s https://codecov.io/bash) -f coverage.info.cleaned || echo "Codecov did not collect coverage reports"
    - language: python
      python: "3.6"
      before_install:
        - cp scripts/ci/texlive.profile $HOME/texlive.profile
      install:
        - "pip install jinja2 Pygments conan"
        - source ./scripts/ci/texlive_install.sh
      addons:
        apt:
          packages:
            - doxygen
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
          - $HOME/.cache/pipenv
          - /nix/
      before_script:
        - git clone https://github.com/mosra/m.css.git
      script:
        - ./m.css/documentation/doxygen.py Doxyfile-mcss
        - find docs/ -type f -name "*" -print0 | xargs -0 sed -i '' -e 's/>Pages</>Wiki</g' || true
      deploy:
        provider: pages
        edge: true
        cleanup: false
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
