trajectory: "../templates/s2-clathrate/single-cage-watOnly.lammpstrj"
variables: "../lua_inputs/iceType/vars.lua"
bulk:
  use: true
  topologicalNetworkCriterion: false
  bondOrderParameters: false
topoOneDim:
  use: false
topoTwoDim:
  use: false